# The "build" workflow produces wheels (and the sdist) for all python
# versions/platforms. Where possible (i.e. the build is not a cross-compile),
# the test suite is also run for the wheel (this test covers fewer
# configurations than the "test" workflow and tox.ini).
name: Build

on:
  workflow_dispatch:
    # Allow this workflow to be run manually (pushing to testpypi instead of pypi)

permissions: {}

env:
  python-version: '3.9'

jobs:
  build_sdist:
    name: Build sdist
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-python@v5
        name: Install Python
        with:
          python-version: ${{ env.python-version }}

      - name: Install setuptools and wheel
        run: pip install setuptools==80.7.1 wheel==0.46.1
      - name: remove speedups.pyi and __init__.pyi
        run: rm -f tornado/speedups.pyi tornado/__init__.pyi
      - name: Check metadata
        run: "python setup.py check"
      - name: Build sdist
        run: "python setup.py sdist && ls -l dist"

      - uses: actions/upload-artifact@v4
        with:
          name: artifacts-sdist
          path: ./dist/tornado-*.tar.gz

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 50
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04-arm, windows-2022, macos-15]

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-python@v5
        name: Install Python
        with:
          python-version: ${{ env.python-version }}

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.22
        env:
          CIBW_BEFORE_BUILD: pip install setuptools==80.7.1 wheel==0.46.1

      - name: Audit ABI3 compliance
        # This may be moved into cibuildwheel itself in the future. See
        # https://github.com/pypa/cibuildwheel/issues/1342
        run: "pip install --index-url 'https://:2025-05-15T23:00:00.000000Z@time-machines-pypi.sealsecurity.io/' abi3audit && abi3audit --verbose --summary ./wheelhouse/*.whl"

      - uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{ matrix.os }}
          path: ./wheelhouse/*.whl
          retention-days: 3

